apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-frontend
  template:
    metadata:        
      labels:
        app: apache-frontend
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: apache-frontend
spec:
  type: ClusterIP
  selector:
    app: apache-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
